version: '3.7'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=digi
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - reverse-proxy
  backend:
    container_name: backend
    build:
      context: ./backend
    command: yarn start
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - reverse-proxy
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: yarn serve
    env_file:
      - .env
    networks:
      - reverse-proxy
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - reverse-proxy
    depends_on:
      - backend
      - frontend

networks:
  reverse-proxy:
    driver: bridge
